### ISSUE TITLE
Requiring multiple stylesheets with the same relative path doesn't work

### ISSUE THREAD

**Issue by lern** [webpack/style-loader#54]
As of b9fdff56e81ead7dfe73a23d82276cef4eb7325d, I'm running into an issue when requiring multiple stylesheets with the same relative path.

The easiest way to reproduce is to use https://github.com/lern/react-starter, which is a fork of https://github.com/webpack/react-starter that I slightly modified to use version `0.10.1` of `style-loader` and added an additional `require` of a stylesheet called `style.css`. If you do a `npm run build`, `npm start`, and navigate to `localhost:8080`, you will see this error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
```

I'm not entirely sure how to debug further, but I've narrowed it down to b9fdff56e81ead7dfe73a23d82276cef4eb7325d and also observed that the issue only happens if I have multiple require statements of the same relative path (eg. `require("./style.css");`), but in different directories (ie. the paths resolve to different files). I don't hit the issue if I run in HMR mode.

**Comment by arnihermann** [comment]
I encountered this issue as well and can confirm that 0.10.0 works but 0.10.1. My config is derived from react-starter but has diverged slightly from it.

**Comment by sokra** [comment]
I think this was fixed by https://github.com/webpack/webpack/commit/026170a8a36c82552f894cf9a6b9f1695552fc42

**Comment by lern** [comment]
@sokra I just tried confirming that using v1.8.5 of webpack and I'm still getting the error. See lern/react-starter@2d63d99b051bf51b81d3542d80e5975e225d8ada if you'd like to reproduce it.

**Comment by sokra** [comment]
I'll check.

**Comment by sokra** [comment]
Don't have a solution yet, but it's the combination of `DedupePlugin` and `ExtractTextPlugin`, when a module is deduped and removed by extraction.

**Comment by lern** [comment]
@sokra thanks, I confirmed it's fixed in webpack master :+1:
